# Utiliser une image officielle Node.js comme image de base
FROM node:14

# Définir le répertoire de travail
WORKDIR /app

# Copier package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier tout le code de l'application
COPY . .

# Exposer le port sur lequel l'application tourne (BrowserSync)
EXPOSE 3000

# Démarrer l'application
CMD ["npm", "start"]
