# Utiliser une image officielle Node.js comme image de base
FROM node:14

# Définir le répertoire de travail
WORKDIR /app

# Copier package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Démarrer l'application
CMD ["npm", "start"]

#CMD ["tail", "-f", "/dev/null"]
